### ISSUE TITLE
RuntimeError: Not compiled with CUDA support

### ISSUE THREAD

**Issue by fishysq** [rusty1s/pyg_autoscale#4]
Hello, thank you very much for your contribution in the large-scale graph training. I also try to run it on the machine. There is a problem now, I hope you can help solve it ,thank you! 
![360截图187903157388109](https://user-images.githubusercontent.com/39077600/130416575-fad2ed37-cad5-4f26-b58b-b055c14145cb.png)

**Comment by rusty1s** [comment]
It seems there is a problem compiling the CUDA code. What's the output of running
```
pyton setup.py clean && rm -rf build && python setup.py install
```

**Comment by fishysq** [comment]
Thank you. I tried it again on windows system, and  actually got a lot of warnings when running pyton setup.py install 
![1](https://user-images.githubusercontent.com/39077600/130548059-42c1f282-1a22-49d6-9f66-db529d7ff41d.png)
![2](https://user-images.githubusercontent.com/39077600/130548070-30e99d02-04c6-4167-bfd5-999471f851d4.png)
![3](https://user-images.githubusercontent.com/39077600/130548076-250a77a6-fdba-4d63-84f4-7a038193312e.png)

**Comment by fishysq** [comment]
> Thank you. I tried it again on windows system, and actually got a lot of warnings when running pyton setup.py install
> ![1](https://user-images.githubusercontent.com/39077600/130548059-42c1f282-1a22-49d6-9f66-db529d7ff41d.png)
> ![2](https://user-images.githubusercontent.com/39077600/130548070-30e99d02-04c6-4167-bfd5-999471f851d4.png)
> ![3](https://user-images.githubusercontent.com/39077600/130548076-250a77a6-fdba-4d63-84f4-7a038193312e.png)

pytorch 1.8.0 
cuda 11.1

**Comment by rusty1s** [comment]
Is there a specific error happening during `python setup.py install` or are those just warnings?

**Comment by fishysq** [comment]
Thank you！just a series of warnings, no errors, when running the program, RuntimeError: No compiled with cuda support



发自我的iPhone


------------------ Original ------------------
From: Matthias Fey ***@***.***&gt;
Date: Tue,Aug 24,2021 3:25 PM
To: rusty1s/pyg_autoscale ***@***.***&gt;
Cc: fishysq ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rusty1s/pyg_autoscale] RuntimeError: Not compiled with CUDA support (#4)





 
Is there a specific error happening during python setup.py install or are those just warnings?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ziyang-Yu** [comment]
Sorry to bother you. I have encountered the same issue showing **RuntimeError: Not compiled with CUDA support**. Running smoothly without errors on small_benchmark but report errors on large_benchmark. Can you help me with it? Thank you very much!
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/80570405/186436038-52fbb1b4-32dc-4102-9b6e-eee4636c78ab.png">

**Comment by rusty1s** [comment]
Thanks for reporting. Does [this](https://github.com/rusty1s/pyg_autoscale/issues/4#issuecomment-906117574) help?

**Comment by Ziyang-Yu** [comment]
> Thanks for reporting. Does [this](https://github.com/rusty1s/pyg_autoscale/issues/4#issuecomment-906117574) help?


Thanks for your reply. Unfortunately, it reports an error.
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/80570405/186576718-e5c47212-b400-47a8-99c6-181d0409adb6.png">

**Comment by rusty1s** [comment]
Can you try to run a fresh install? What's the output log of `python setup.py develop`?

Note that I just added better support for this in master. You can now enforce CUDA installation by running
```
FORCE_CUDA=1 python setup.py develop
```
see https://github.com/rusty1s/pyg_autoscale/commit/6c2d04c267ce313ee4a2bf97bf21a11b70803d5b

**Comment by Ziyang-Yu** [comment]
> Can you try to run a fresh install? What's the output log of `python setup.py develop`?
> 
> Note that I just added better support for this in master. You can now enforce CUDA installation by running
> 
> ```
> FORCE_CUDA=1 python setup.py develop
> ```
> 
> see [6c2d04c](https://github.com/rusty1s/pyg_autoscale/commit/6c2d04c267ce313ee4a2bf97bf21a11b70803d5b)

It solves my problem. Thank you very much!
